spring:
  datasource:           # datasource ??
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maindb
    username: sa
    password:
  h2:
    console:
      enabled: true     # h2 console ??
